# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/interface
# Target is an application:  ../../fet

SOURCES += fet.cpp \
           helpaboutform.cpp \
           helpfaqform.cpp \
           helptipsform.cpp \
           helpinstructionsform.cpp \
           activitiesform.cpp \
           addactivityform.cpp \
           modifyactivityform.cpp \
\
           subactivitiesform.cpp \
           modifysubactivityform.cpp \
\
           addroomform.cpp \
           modifyroomform.cpp \
           addbuildingform.cpp \
           modifybuildingform.cpp \
           addstudentsyearform.cpp \
           modifystudentsyearform.cpp \
           addstudentsgroupform.cpp \
           addstudentssubgroupform.cpp \
           modifystudentsgroupform.cpp \
           modifystudentssubgroupform.cpp \
           addconstraintactivitypreferredtimeslotsform.cpp \
           modifyconstraintactivitypreferredtimeslotsform.cpp \
           addconstraintactivitypreferredstartingtimesform.cpp \
           modifyconstraintactivitypreferredstartingtimesform.cpp \
           addconstraintroomnotavailabletimesform.cpp \
           constraintroomnotavailabletimesform.cpp \
           modifyconstraintroomnotavailabletimesform.cpp \
           addconstraintactivitypreferredroomform.cpp \
           constraintactivitypreferredroomform.cpp \
           modifyconstraintactivitypreferredroomform.cpp \
           addconstraintsubjectpreferredroomform.cpp \
           constraintsubjectpreferredroomform.cpp \
           modifyconstraintsubjectpreferredroomform.cpp \
           addconstraintsubjectpreferredroomsform.cpp \
           constraintsubjectpreferredroomsform.cpp \
           modifyconstraintsubjectpreferredroomsform.cpp \
           addconstraintsubjectactivitytagpreferredroomform.cpp \
           constraintsubjectactivitytagpreferredroomform.cpp \
           modifyconstraintsubjectactivitytagpreferredroomform.cpp \
           addconstraintsubjectactivitytagpreferredroomsform.cpp \
           constraintsubjectactivitytagpreferredroomsform.cpp \
           modifyconstraintsubjectactivitytagpreferredroomsform.cpp \
           addconstraintstudentssethomeroomform.cpp \
\
           addconstraintstudentssetmaxbuildingchangesperdayform.cpp \
           constraintstudentssetmaxbuildingchangesperdayform.cpp \
           modifyconstraintstudentssetmaxbuildingchangesperdayform.cpp \
           addconstraintstudentsmaxbuildingchangesperdayform.cpp \
           constraintstudentsmaxbuildingchangesperdayform.cpp \
           modifyconstraintstudentsmaxbuildingchangesperdayform.cpp \
           addconstraintstudentssetmaxbuildingchangesperweekform.cpp \
           constraintstudentssetmaxbuildingchangesperweekform.cpp \
           modifyconstraintstudentssetmaxbuildingchangesperweekform.cpp \
           addconstraintstudentsmaxbuildingchangesperweekform.cpp \
           constraintstudentsmaxbuildingchangesperweekform.cpp \
           modifyconstraintstudentsmaxbuildingchangesperweekform.cpp \
           addconstraintstudentssetmingapsbetweenbuildingchangesform.cpp \
           constraintstudentssetmingapsbetweenbuildingchangesform.cpp \
           modifyconstraintstudentssetmingapsbetweenbuildingchangesform.cpp \
           addconstraintstudentsmingapsbetweenbuildingchangesform.cpp \
           constraintstudentsmingapsbetweenbuildingchangesform.cpp \
           modifyconstraintstudentsmingapsbetweenbuildingchangesform.cpp \
\
           addconstraintteachermaxbuildingchangesperdayform.cpp \
           constraintteachermaxbuildingchangesperdayform.cpp \
           modifyconstraintteachermaxbuildingchangesperdayform.cpp \
           addconstraintteachersmaxbuildingchangesperdayform.cpp \
           constraintteachersmaxbuildingchangesperdayform.cpp \
           modifyconstraintteachersmaxbuildingchangesperdayform.cpp \
           addconstraintteachermaxbuildingchangesperweekform.cpp \
           constraintteachermaxbuildingchangesperweekform.cpp \
           modifyconstraintteachermaxbuildingchangesperweekform.cpp \
           addconstraintteachersmaxbuildingchangesperweekform.cpp \
           constraintteachersmaxbuildingchangesperweekform.cpp \
           modifyconstraintteachersmaxbuildingchangesperweekform.cpp \
           addconstraintteachermingapsbetweenbuildingchangesform.cpp \
           constraintteachermingapsbetweenbuildingchangesform.cpp \
           modifyconstraintteachermingapsbetweenbuildingchangesform.cpp \
           addconstraintteachersmingapsbetweenbuildingchangesform.cpp \
           constraintteachersmingapsbetweenbuildingchangesform.cpp \
           modifyconstraintteachersmingapsbetweenbuildingchangesform.cpp \
\
           constraintstudentssethomeroomform.cpp \
           modifyconstraintstudentssethomeroomform.cpp \
           addconstraintstudentssethomeroomsform.cpp \
           constraintstudentssethomeroomsform.cpp \
           modifyconstraintstudentssethomeroomsform.cpp \
           addconstraintteacherhomeroomform.cpp \
           constraintteacherhomeroomform.cpp \
           modifyconstraintteacherhomeroomform.cpp \
           addconstraintteacherhomeroomsform.cpp \
           constraintteacherhomeroomsform.cpp \
           modifyconstraintteacherhomeroomsform.cpp \
           addconstraintactivitypreferredroomsform.cpp \
           constraintactivitypreferredroomsform.cpp \
           modifyconstraintactivitypreferredroomsform.cpp \
           alltimeconstraintsform.cpp \
           allspaceconstraintsform.cpp \
           groupsform.cpp \
           subgroupsform.cpp \
           subjectsform.cpp \
           activitytagsform.cpp \
           teachersform.cpp \
           timetablegenerateform.cpp \
           timetablegeneratemultipleform.cpp \
           fetmainform.cpp \
			centerwidgetonscreen.cpp \
           settingstimetablehtmllevelform.cpp \
           timetableviewstudentsform.cpp \
           timetableviewroomsform.cpp \
           yearsform.cpp \
           timetableshowconflictsform.cpp \
           timetableviewteachersform.cpp \
           hoursform.cpp \
           daysform.cpp \
           ../engine/activity.cpp \
           ../engine/solution.cpp \
           ../engine/timetable.cpp \
           ../engine/rules.cpp \
		   ../engine/import.cpp \
		   ../engine/export.cpp \
           ../engine/generate_pre.cpp \
           ../engine/timeconstraint.cpp \
           ../engine/spaceconstraint.cpp \
           ../engine/studentsset.cpp \
           ../engine/teacher.cpp \
           ../engine/subject.cpp \
           ../engine/activitytag.cpp \
           ../engine/room.cpp \
           ../engine/building.cpp \
           ../engine/timetable_defs.cpp \
		   ../engine/generate.cpp \
		   ../engine/timetableexport.cpp \
		   ../engine/statisticsexport.cpp \
           roomsform.cpp \
           buildingsform.cpp \
           \
           constraintactivitiespreferredtimeslotsform.cpp \
           addconstraintactivitiespreferredtimeslotsform.cpp \
           modifyconstraintactivitiespreferredtimeslotsform.cpp \
           constraintactivitiespreferredstartingtimesform.cpp \
           addconstraintactivitiespreferredstartingtimesform.cpp \
           modifyconstraintactivitiespreferredstartingtimesform.cpp \
           \
           constraintsubactivitiespreferredtimeslotsform.cpp \
           addconstraintsubactivitiespreferredtimeslotsform.cpp \
           modifyconstraintsubactivitiespreferredtimeslotsform.cpp \
           constraintsubactivitiespreferredstartingtimesform.cpp \
           addconstraintsubactivitiespreferredstartingtimesform.cpp \
           modifyconstraintsubactivitiespreferredstartingtimesform.cpp \
           \
           constraintactivitiessamestartingtimeform.cpp \
           addconstraintactivitiessamestartingtimeform.cpp \
\
           constraintactivitiessamestartinghourform.cpp \
           addconstraintactivitiessamestartinghourform.cpp \
\
           constraintactivitiessamestartingdayform.cpp \
           addconstraintactivitiessamestartingdayform.cpp \
           modifyconstraintactivitiessamestartingdayform.cpp \
\
		   constraintteachernotavailabletimesform.cpp \
		   addconstraintteachernotavailabletimesform.cpp \
		   modifyconstraintteachernotavailabletimesform.cpp \
		   constraintbasiccompulsorytimeform.cpp \
		   addconstraintbasiccompulsorytimeform.cpp \
		   modifyconstraintbasiccompulsorytimeform.cpp \
		   constraintbasiccompulsoryspaceform.cpp \
		   addconstraintbasiccompulsoryspaceform.cpp \
		   modifyconstraintbasiccompulsoryspaceform.cpp \
		   constraintstudentssetnotavailabletimesform.cpp \
		   addconstraintstudentssetnotavailabletimesform.cpp \
		   modifyconstraintstudentssetnotavailabletimesform.cpp \
		   constraintbreaktimesform.cpp \
		   addconstraintbreaktimesform.cpp \
		   modifyconstraintbreaktimesform.cpp \
		   constraintteachermaxdaysperweekform.cpp \
		   addconstraintteachermaxdaysperweekform.cpp \
		   modifyconstraintteachermaxdaysperweekform.cpp \
\
		   constraintteacherintervalmaxdaysperweekform.cpp \
		   addconstraintteacherintervalmaxdaysperweekform.cpp \
		   modifyconstraintteacherintervalmaxdaysperweekform.cpp \
\
		   constraintstudentssetintervalmaxdaysperweekform.cpp \
		   addconstraintstudentssetintervalmaxdaysperweekform.cpp \
		   modifyconstraintstudentssetintervalmaxdaysperweekform.cpp \
\
		   constraintstudentsintervalmaxdaysperweekform.cpp \
		   addconstraintstudentsintervalmaxdaysperweekform.cpp \
		   modifyconstraintstudentsintervalmaxdaysperweekform.cpp \
\
		   constraintteachersintervalmaxdaysperweekform.cpp \
		   addconstraintteachersintervalmaxdaysperweekform.cpp \
		   modifyconstraintteachersintervalmaxdaysperweekform.cpp \
\
		   constraintteachersmaxhoursdailyform.cpp \
		   addconstraintteachersmaxhoursdailyform.cpp \
		   modifyconstraintteachersmaxhoursdailyform.cpp \
		   constraintteachermaxhoursdailyform.cpp \
		   addconstraintteachermaxhoursdailyform.cpp \
		   modifyconstraintteachermaxhoursdailyform.cpp \
\
		   constraintteachersmaxhourscontinuouslyform.cpp \
		   addconstraintteachersmaxhourscontinuouslyform.cpp \
		   modifyconstraintteachersmaxhourscontinuouslyform.cpp \
		   constraintteachermaxhourscontinuouslyform.cpp \
		   addconstraintteachermaxhourscontinuouslyform.cpp \
		   modifyconstraintteachermaxhourscontinuouslyform.cpp \
\
		   constraintteachersactivitytagmaxhourscontinuouslyform.cpp \
		   addconstraintteachersactivitytagmaxhourscontinuouslyform.cpp \
		   modifyconstraintteachersactivitytagmaxhourscontinuouslyform.cpp \
		   constraintteacheractivitytagmaxhourscontinuouslyform.cpp \
		   addconstraintteacheractivitytagmaxhourscontinuouslyform.cpp \
		   modifyconstraintteacheractivitytagmaxhourscontinuouslyform.cpp \
\
		   constraintteachersminhoursdailyform.cpp \
		   addconstraintteachersminhoursdailyform.cpp \
		   modifyconstraintteachersminhoursdailyform.cpp \
		   constraintteacherminhoursdailyform.cpp \
		   addconstraintteacherminhoursdailyform.cpp \
		   modifyconstraintteacherminhoursdailyform.cpp \
		   constraintactivitypreferredstartingtimeform.cpp \
		   addconstraintactivitypreferredstartingtimeform.cpp \
		   modifyconstraintactivitypreferredstartingtimeform.cpp \
		   constraintactivityendsstudentsdayform.cpp \
		   addconstraintactivityendsstudentsdayform.cpp \
		   modifyconstraintactivityendsstudentsdayform.cpp \
\
		   constraintactivitiesendstudentsdayform.cpp \
		   addconstraintactivitiesendstudentsdayform.cpp \
		   modifyconstraintactivitiesendstudentsdayform.cpp \
\
		   constraintstudentssetmaxgapsperweekform.cpp \
		   addconstraintstudentssetmaxgapsperweekform.cpp \
		   modifyconstraintstudentssetmaxgapsperweekform.cpp \
		   constraintstudentsmaxgapsperweekform.cpp \
		   addconstraintstudentsmaxgapsperweekform.cpp \
		   modifyconstraintstudentsmaxgapsperweekform.cpp \
		   constraintteachersmaxgapsperweekform.cpp \
		   constraintteachermaxgapsperweekform.cpp \
		   addconstraintteachersmaxgapsperweekform.cpp \
		   modifyconstraintteachersmaxgapsperweekform.cpp \
		   addconstraintteachermaxgapsperweekform.cpp \
		   modifyconstraintteachermaxgapsperweekform.cpp \
		   constraintteachersmaxgapsperdayform.cpp \
		   constraintteachermaxgapsperdayform.cpp \
		   addconstraintteachersmaxgapsperdayform.cpp \
		   modifyconstraintteachersmaxgapsperdayform.cpp \
		   addconstraintteachermaxgapsperdayform.cpp \
		   modifyconstraintteachermaxgapsperdayform.cpp \
		   constraintstudentsearlymaxbeginningsatsecondhourform.cpp \
		   addconstraintstudentsearlymaxbeginningsatsecondhourform.cpp \
		   modifyconstraintstudentsearlymaxbeginningsatsecondhourform.cpp \
		   constraintstudentssetearlymaxbeginningsatsecondhourform.cpp \
		   addconstraintstudentssetearlymaxbeginningsatsecondhourform.cpp \
		   modifyconstraintstudentssetearlymaxbeginningsatsecondhourform.cpp \
\
		   constraintstudentssetmaxhoursdailyform.cpp \
		   addconstraintstudentssetmaxhoursdailyform.cpp \
		   modifyconstraintstudentssetmaxhoursdailyform.cpp \
		   constraintstudentsmaxhoursdailyform.cpp \
		   addconstraintstudentsmaxhoursdailyform.cpp \
		   modifyconstraintstudentsmaxhoursdailyform.cpp \
\
		   constraintstudentssetmaxhourscontinuouslyform.cpp \
		   addconstraintstudentssetmaxhourscontinuouslyform.cpp \
		   modifyconstraintstudentssetmaxhourscontinuouslyform.cpp \
		   constraintstudentsmaxhourscontinuouslyform.cpp \
		   addconstraintstudentsmaxhourscontinuouslyform.cpp \
		   modifyconstraintstudentsmaxhourscontinuouslyform.cpp \
\
		   constraintstudentssetactivitytagmaxhourscontinuouslyform.cpp \
		   addconstraintstudentssetactivitytagmaxhourscontinuouslyform.cpp \
		   modifyconstraintstudentssetactivitytagmaxhourscontinuouslyform.cpp \
		   constraintstudentsactivitytagmaxhourscontinuouslyform.cpp \
		   addconstraintstudentsactivitytagmaxhourscontinuouslyform.cpp \
		   modifyconstraintstudentsactivitytagmaxhourscontinuouslyform.cpp \
\
		   constraintstudentssetminhoursdailyform.cpp \
		   addconstraintstudentssetminhoursdailyform.cpp \
		   modifyconstraintstudentssetminhoursdailyform.cpp \
		   constraintstudentsminhoursdailyform.cpp \
		   addconstraintstudentsminhoursdailyform.cpp \
		   modifyconstraintstudentsminhoursdailyform.cpp \
		   constraintactivitiesnotoverlappingform.cpp \
		   addconstraintactivitiesnotoverlappingform.cpp \
		   modifyconstraintactivitiesnotoverlappingform.cpp \
		   constraint2activitiesconsecutiveform.cpp \
		   addconstraint2activitiesconsecutiveform.cpp \
		   modifyconstraint2activitiesconsecutiveform.cpp \
\
		   constraint2activitiesgroupedform.cpp \
		   addconstraint2activitiesgroupedform.cpp \
		   modifyconstraint2activitiesgroupedform.cpp \
\
		   constraint2activitiesorderedform.cpp \
		   addconstraint2activitiesorderedform.cpp \
		   modifyconstraint2activitiesorderedform.cpp \
\
		   constraintminndaysbetweenactivitiesform.cpp \
		   addconstraintminndaysbetweenactivitiesform.cpp \
		   modifyconstraintminndaysbetweenactivitiesform.cpp \
\
		   constraintmingapsbetweenactivitiesform.cpp \
		   addconstraintmingapsbetweenactivitiesform.cpp \
		   modifyconstraintmingapsbetweenactivitiesform.cpp \
\
		   constraintactivitypreferredtimeslotsform.cpp \
		   constraintactivitypreferredstartingtimesform.cpp \
		   modifyconstraintactivitiessamestartingtimeform.cpp \
		   modifyconstraintactivitiessamestartinghourform.cpp \
		   institutionnameform.cpp \
		   commentsform.cpp \
		   teachersstatisticsform.cpp \
		   subjectsstatisticsform.cpp \
		   studentsstatisticsform.cpp \
		   httpget.cpp \
		   splityearform.cpp \
\
		   changeminndaysselectivelyform.cpp \
\
		   spreadminndaysconstraints5daysform.cpp \
		   spreadconfirmationform.cpp \
\
		   removeredundantform.cpp \
		   removeredundantconfirmationform.cpp \
\
			lockunlock.cpp
HEADERS += fet.h \
           helpaboutform.h \
           helpfaqform.h \
           helptipsform.h \
           helpinstructionsform.h \
           activitiesform.h \
           addactivityform.h \
           modifyactivityform.h \
\
           subactivitiesform.h \
           modifysubactivityform.h \
\
           addroomform.h \
           modifyroomform.h \
           addbuildingform.h \
           modifybuildingform.h \
           addstudentsyearform.h \
           modifystudentsyearform.h \
           addstudentsgroupform.h \
           addstudentssubgroupform.h \
           modifystudentsgroupform.h \
           modifystudentssubgroupform.h \
           addconstraintactivitypreferredtimeslotsform.h \
           modifyconstraintactivitypreferredtimeslotsform.h \
           addconstraintactivitypreferredstartingtimesform.h \
           modifyconstraintactivitypreferredstartingtimesform.h \
           addconstraintroomnotavailabletimesform.h \
           constraintroomnotavailabletimesform.h \
           modifyconstraintroomnotavailabletimesform.h \
           addconstraintactivitypreferredroomform.h \
           constraintactivitypreferredroomform.h \
           modifyconstraintactivitypreferredroomform.h \
           addconstraintsubjectpreferredroomform.h \
           constraintsubjectpreferredroomform.h \
           modifyconstraintsubjectpreferredroomform.h \
           addconstraintsubjectactivitytagpreferredroomform.h \
           constraintsubjectactivitytagpreferredroomform.h \
           modifyconstraintsubjectactivitytagpreferredroomform.h \
           addconstraintsubjectpreferredroomsform.h \
           constraintsubjectpreferredroomsform.h \
           modifyconstraintsubjectpreferredroomsform.h \
           addconstraintsubjectactivitytagpreferredroomsform.h \
           constraintsubjectactivitytagpreferredroomsform.h \
           modifyconstraintsubjectactivitytagpreferredroomsform.h \
           addconstraintstudentssethomeroomform.h \
           constraintstudentssethomeroomform.h \
           modifyconstraintstudentssethomeroomform.h \
           addconstraintstudentssethomeroomsform.h \
           constraintstudentssethomeroomsform.h \
           modifyconstraintstudentssethomeroomsform.h \
\
           addconstraintstudentssetmaxbuildingchangesperdayform.h \
           constraintstudentssetmaxbuildingchangesperdayform.h \
           modifyconstraintstudentssetmaxbuildingchangesperdayform.h \
           addconstraintstudentsmaxbuildingchangesperdayform.h \
           constraintstudentsmaxbuildingchangesperdayform.h \
           modifyconstraintstudentsmaxbuildingchangesperdayform.h \
           addconstraintstudentssetmaxbuildingchangesperweekform.h \
           constraintstudentssetmaxbuildingchangesperweekform.h \
           modifyconstraintstudentssetmaxbuildingchangesperweekform.h \
           addconstraintstudentsmaxbuildingchangesperweekform.h \
           constraintstudentsmaxbuildingchangesperweekform.h \
           modifyconstraintstudentsmaxbuildingchangesperweekform.h \
           addconstraintstudentssetmingapsbetweenbuildingchangesform.h \
           constraintstudentssetmingapsbetweenbuildingchangesform.h \
           modifyconstraintstudentssetmingapsbetweenbuildingchangesform.h \
           addconstraintstudentsmingapsbetweenbuildingchangesform.h \
           constraintstudentsmingapsbetweenbuildingchangesform.h \
           modifyconstraintstudentsmingapsbetweenbuildingchangesform.h \
\
           addconstraintteachermaxbuildingchangesperdayform.h \
           constraintteachermaxbuildingchangesperdayform.h \
           modifyconstraintteachermaxbuildingchangesperdayform.h \
           addconstraintteachersmaxbuildingchangesperdayform.h \
           constraintteachersmaxbuildingchangesperdayform.h \
           modifyconstraintteachersmaxbuildingchangesperdayform.h \
           addconstraintteachermaxbuildingchangesperweekform.h \
           constraintteachermaxbuildingchangesperweekform.h \
           modifyconstraintteachermaxbuildingchangesperweekform.h \
           addconstraintteachersmaxbuildingchangesperweekform.h \
           constraintteachersmaxbuildingchangesperweekform.h \
           modifyconstraintteachersmaxbuildingchangesperweekform.h \
           addconstraintteachermingapsbetweenbuildingchangesform.h \
           constraintteachermingapsbetweenbuildingchangesform.h \
           modifyconstraintteachermingapsbetweenbuildingchangesform.h \
           addconstraintteachersmingapsbetweenbuildingchangesform.h \
           constraintteachersmingapsbetweenbuildingchangesform.h \
           modifyconstraintteachersmingapsbetweenbuildingchangesform.h \
\
           addconstraintteacherhomeroomform.h \
           constraintteacherhomeroomform.h \
           modifyconstraintteacherhomeroomform.h \
           addconstraintteacherhomeroomsform.h \
           constraintteacherhomeroomsform.h \
           modifyconstraintteacherhomeroomsform.h \
           addconstraintactivitypreferredroomsform.h \
           constraintactivitypreferredroomsform.h \
           modifyconstraintactivitypreferredroomsform.h \
           alltimeconstraintsform.h \
           allspaceconstraintsform.h \
           groupsform.h \
           subgroupsform.h \
           subjectsform.h \
           activitytagsform.h \
           teachersform.h \
           timetablegenerateform.h \
           timetablegeneratemultipleform.h \
           fetmainform.h \
			centerwidgetonscreen.h \
           settingstimetablehtmllevelform.h \
           timetableviewstudentsform.h \
           timetableviewroomsform.h \
           yearsform.h \
           timetableshowconflictsform.h \
           timetableviewteachersform.h \
           hoursform.h \
           daysform.h \
           ../engine/activity.h \
           ../engine/solution.h \
           ../engine/timetable.h \
           ../engine/rules.h \
		   ../engine/import.h \
		   ../engine/export.h \
           ../engine/generate_pre.h \
           ../engine/timeconstraint.h \
           ../engine/spaceconstraint.h \
           ../engine/timetable_defs.h \
           ../engine/studentsset.h \
           ../engine/teacher.h \
           ../engine/subject.h \
           ../engine/activitytag.h \
           ../engine/room.h \
           ../engine/building.h \
		   ../engine/generate.h \
		   ../engine/timetableexport.h \
		   ../engine/statisticsexport.h \
           roomsform.h \
           buildingsform.h \
           \
           constraintactivitiespreferredtimeslotsform.h \
           addconstraintactivitiespreferredtimeslotsform.h \
           constraintactivitiespreferredstartingtimesform.h \
           addconstraintactivitiespreferredstartingtimesform.h \
           constraintactivitiessamestartingtimeform.h \
           addconstraintactivitiessamestartingtimeform.h \
           \
           constraintsubactivitiespreferredtimeslotsform.h \
           addconstraintsubactivitiespreferredtimeslotsform.h \
           modifyconstraintsubactivitiespreferredtimeslotsform.h \
           constraintsubactivitiespreferredstartingtimesform.h \
           addconstraintsubactivitiespreferredstartingtimesform.h \
           modifyconstraintsubactivitiespreferredstartingtimesform.h \
           \
\
           constraintactivitiessamestartinghourform.h \
           addconstraintactivitiessamestartinghourform.h \
\
           constraintactivitiessamestartingdayform.h \
           addconstraintactivitiessamestartingdayform.h \
           modifyconstraintactivitiessamestartingdayform.h \
\
		   constraintteachernotavailabletimesform.h \
		   addconstraintteachernotavailabletimesform.h \
		   modifyconstraintteachernotavailabletimesform.h \
		   constraintbasiccompulsorytimeform.h \
		   addconstraintbasiccompulsorytimeform.h \
		   modifyconstraintbasiccompulsorytimeform.h \
		   constraintbasiccompulsoryspaceform.h \
		   addconstraintbasiccompulsoryspaceform.h \
		   modifyconstraintbasiccompulsoryspaceform.h \
		   constraintstudentssetnotavailabletimesform.h \
		   addconstraintstudentssetnotavailabletimesform.h \
		   modifyconstraintstudentssetnotavailabletimesform.h \
		   constraintbreaktimesform.h \
		   addconstraintbreaktimesform.h \
		   modifyconstraintbreaktimesform.h \
		   constraintteachermaxdaysperweekform.h \
		   addconstraintteachermaxdaysperweekform.h \
		   modifyconstraintteachermaxdaysperweekform.h \
\
		   constraintteacherintervalmaxdaysperweekform.h \
		   addconstraintteacherintervalmaxdaysperweekform.h \
		   modifyconstraintteacherintervalmaxdaysperweekform.h \
\
		   constraintstudentssetintervalmaxdaysperweekform.h \
		   addconstraintstudentssetintervalmaxdaysperweekform.h \
		   modifyconstraintstudentssetintervalmaxdaysperweekform.h \
\
		   constraintstudentsintervalmaxdaysperweekform.h \
		   addconstraintstudentsintervalmaxdaysperweekform.h \
		   modifyconstraintstudentsintervalmaxdaysperweekform.h \
\
		   constraintteachersintervalmaxdaysperweekform.h \
		   addconstraintteachersintervalmaxdaysperweekform.h \
		   modifyconstraintteachersintervalmaxdaysperweekform.h \
\
		   constraintteachersmaxhoursdailyform.h \
		   addconstraintteachersmaxhoursdailyform.h \
		   modifyconstraintteachersmaxhoursdailyform.h \
		   constraintteachermaxhoursdailyform.h \
		   addconstraintteachermaxhoursdailyform.h \
		   modifyconstraintteachermaxhoursdailyform.h \
\
		   constraintteachersmaxhourscontinuouslyform.h \
		   addconstraintteachersmaxhourscontinuouslyform.h \
		   modifyconstraintteachersmaxhourscontinuouslyform.h \
		   constraintteachermaxhourscontinuouslyform.h \
		   addconstraintteachermaxhourscontinuouslyform.h \
		   modifyconstraintteachermaxhourscontinuouslyform.h \
\
		   constraintteachersactivitytagmaxhourscontinuouslyform.h \
		   addconstraintteachersactivitytagmaxhourscontinuouslyform.h \
		   modifyconstraintteachersactivitytagmaxhourscontinuouslyform.h \
		   constraintteacheractivitytagmaxhourscontinuouslyform.h \
		   addconstraintteacheractivitytagmaxhourscontinuouslyform.h \
		   modifyconstraintteacheractivitytagmaxhourscontinuouslyform.h \
\
		   constraintteachersminhoursdailyform.h \
		   addconstraintteachersminhoursdailyform.h \
		   modifyconstraintteachersminhoursdailyform.h \
		   constraintteacherminhoursdailyform.h \
		   addconstraintteacherminhoursdailyform.h \
		   modifyconstraintteacherminhoursdailyform.h \
		   constraintactivitypreferredstartingtimeform.h \
		   addconstraintactivitypreferredstartingtimeform.h \
		   modifyconstraintactivitypreferredstartingtimeform.h \
		   constraintactivityendsstudentsdayform.h \
		   addconstraintactivityendsstudentsdayform.h \
		   modifyconstraintactivityendsstudentsdayform.h \
\
		   constraintactivitiesendstudentsdayform.h \
		   addconstraintactivitiesendstudentsdayform.h \
		   modifyconstraintactivitiesendstudentsdayform.h \
\
		   constraintstudentssetmaxgapsperweekform.h \
		   addconstraintstudentssetmaxgapsperweekform.h \
		   modifyconstraintstudentssetmaxgapsperweekform.h \
		   constraintstudentsmaxgapsperweekform.h \
		   addconstraintstudentsmaxgapsperweekform.h \
		   modifyconstraintstudentsmaxgapsperweekform.h \
		   constraintteachersmaxgapsperweekform.h \
		   addconstraintteachersmaxgapsperweekform.h \
		   modifyconstraintteachersmaxgapsperweekform.h \
		   constraintteachermaxgapsperweekform.h \
		   addconstraintteachermaxgapsperweekform.h \
		   modifyconstraintteachermaxgapsperweekform.h \
		   constraintteachersmaxgapsperdayform.h \
		   addconstraintteachersmaxgapsperdayform.h \
		   modifyconstraintteachersmaxgapsperdayform.h \
		   constraintteachermaxgapsperdayform.h \
		   addconstraintteachermaxgapsperdayform.h \
		   modifyconstraintteachermaxgapsperdayform.h \
		   constraintstudentsearlymaxbeginningsatsecondhourform.h \
		   addconstraintstudentsearlymaxbeginningsatsecondhourform.h \
		   modifyconstraintstudentsearlymaxbeginningsatsecondhourform.h \
		   constraintstudentssetearlymaxbeginningsatsecondhourform.h \
		   addconstraintstudentssetearlymaxbeginningsatsecondhourform.h \
		   modifyconstraintstudentssetearlymaxbeginningsatsecondhourform.h \
\
		   constraintstudentssetmaxhoursdailyform.h \
		   addconstraintstudentssetmaxhoursdailyform.h \
		   modifyconstraintstudentssetmaxhoursdailyform.h \
		   constraintstudentsmaxhoursdailyform.h \
		   addconstraintstudentsmaxhoursdailyform.h \
		   modifyconstraintstudentsmaxhoursdailyform.h \
\
		   constraintstudentssetmaxhourscontinuouslyform.h \
		   addconstraintstudentssetmaxhourscontinuouslyform.h \
		   modifyconstraintstudentssetmaxhourscontinuouslyform.h \
		   constraintstudentsmaxhourscontinuouslyform.h \
		   addconstraintstudentsmaxhourscontinuouslyform.h \
		   modifyconstraintstudentsmaxhourscontinuouslyform.h \
\
		   constraintstudentssetactivitytagmaxhourscontinuouslyform.h \
		   addconstraintstudentssetactivitytagmaxhourscontinuouslyform.h \
		   modifyconstraintstudentssetactivitytagmaxhourscontinuouslyform.h \
		   constraintstudentsactivitytagmaxhourscontinuouslyform.h \
		   addconstraintstudentsactivitytagmaxhourscontinuouslyform.h \
		   modifyconstraintstudentsactivitytagmaxhourscontinuouslyform.h \
\
		   constraintstudentssetminhoursdailyform.h \
		   addconstraintstudentssetminhoursdailyform.h \
		   modifyconstraintstudentssetminhoursdailyform.h \
		   constraintstudentsminhoursdailyform.h \
		   addconstraintstudentsminhoursdailyform.h \
		   modifyconstraintstudentsminhoursdailyform.h \
		   constraintactivitiesnotoverlappingform.h \
		   addconstraintactivitiesnotoverlappingform.h \
		   modifyconstraintactivitiesnotoverlappingform.h \
\
		   constraint2activitiesconsecutiveform.h \
		   addconstraint2activitiesconsecutiveform.h \
		   modifyconstraint2activitiesconsecutiveform.h \
\
		   constraint2activitiesgroupedform.h \
		   addconstraint2activitiesgroupedform.h \
		   modifyconstraint2activitiesgroupedform.h \
\
		   constraint2activitiesorderedform.h \
		   addconstraint2activitiesorderedform.h \
		   modifyconstraint2activitiesorderedform.h \
\
		   constraintminndaysbetweenactivitiesform.h \
		   addconstraintminndaysbetweenactivitiesform.h \
		   modifyconstraintminndaysbetweenactivitiesform.h \
\
		   constraintmingapsbetweenactivitiesform.h \
		   addconstraintmingapsbetweenactivitiesform.h \
		   modifyconstraintmingapsbetweenactivitiesform.h \
\
		   constraintactivitypreferredtimeslotsform.h \
           modifyconstraintactivitiespreferredtimeslotsform.h \
		   constraintactivitypreferredstartingtimesform.h \
           modifyconstraintactivitiespreferredstartingtimesform.h \
		   modifyconstraintactivitiessamestartingtimeform.h \
		   modifyconstraintactivitiessamestartinghourform.h \
		   institutionnameform.h \
		   commentsform.h \
		   teachersstatisticsform.h \
		   subjectsstatisticsform.h \
		   studentsstatisticsform.h \
		   httpget.h \
		   splityearform.h\
\
		   changeminndaysselectivelyform.h \
\
		   spreadminndaysconstraints5daysform.h \
		   spreadconfirmationform.h \
\
		   removeredundantform.h \
		   removeredundantconfirmationform.h \
\
			lockunlock.h
TRANSLATIONS += ../../translations/fet_ro.ts \
				../../translations/fet_ca.ts \
                ../../translations/fet_fr.ts \
                ../../translations/fet_ms.ts \
                ../../translations/fet_pl.ts \
                ../../translations/fet_tr.ts \
                ../../translations/fet_nl.ts \
                ../../translations/fet_de.ts \
                ../../translations/fet_mk.ts \
                ../../translations/fet_hu.ts \
				../../translations/fet_es.ts \
				../../translations/fet_el.ts \
				../../translations/fet_ar.ts \
				../../translations/fet_id.ts \
				../../translations/fet_it.ts \
				../../translations/fet_lt.ts \
				../../translations/fet_untranslated.ts
FORMS+=  fetmainform_template.ui \
	helpaboutform_template.ui \
	teachersstatisticsform_template.ui \
	subjectsstatisticsform_template.ui \
	studentsstatisticsform_template.ui \
	settingstimetablehtmllevelform_template.ui \
\
	changeminndaysselectivelyform_template.ui \
	spreadminndaysconstraints5daysform_template.ui \
	spreadconfirmationform_template.ui \
\
	removeredundantform_template.ui \
	removeredundantconfirmationform_template.ui
#The following line was changed from FORMS to FORMS3 by qt3to4
FORMS3 += helpfaqform_template.ui \
		 helptipsform_template.ui \
		 helpinstructionsform_template.ui \
         activitiesform_template.ui \
         addactivityform_template.ui \
         modifyactivityform_template.ui \
\
         subactivitiesform_template.ui \
         modifysubactivityform_template.ui \
\
         addroomform_template.ui \
         modifyroomform_template.ui \
         addbuildingform_template.ui \
         modifybuildingform_template.ui \
         addstudentsyearform_template.ui \
         modifystudentsyearform_template.ui \
         addstudentsgroupform_template.ui \
         addstudentssubgroupform_template.ui \
         modifystudentsgroupform_template.ui \
         modifystudentssubgroupform_template.ui \
         addconstraintactivitypreferredtimeslotsform_template.ui \
         modifyconstraintactivitypreferredtimeslotsform_template.ui \
         addconstraintactivitypreferredstartingtimesform_template.ui \
         modifyconstraintactivitypreferredstartingtimesform_template.ui \
         addconstraintroomnotavailabletimesform_template.ui \
         constraintroomnotavailabletimesform_template.ui \
         modifyconstraintroomnotavailabletimesform_template.ui \
         addconstraintactivitypreferredroomform_template.ui \
         constraintactivitypreferredroomform_template.ui \
         modifyconstraintactivitypreferredroomform_template.ui \
         addconstraintsubjectpreferredroomform_template.ui \
         constraintsubjectpreferredroomform_template.ui \
         modifyconstraintsubjectpreferredroomform_template.ui \
		 addconstraintsubjectactivitytagpreferredroomform_template.ui \
         constraintsubjectactivitytagpreferredroomform_template.ui \
         modifyconstraintsubjectactivitytagpreferredroomform_template.ui \
         addconstraintsubjectpreferredroomsform_template.ui \
         constraintsubjectpreferredroomsform_template.ui \
         modifyconstraintsubjectpreferredroomsform_template.ui \
		 addconstraintsubjectactivitytagpreferredroomsform_template.ui \
         constraintsubjectactivitytagpreferredroomsform_template.ui \
         modifyconstraintsubjectactivitytagpreferredroomsform_template.ui \
         addconstraintstudentssethomeroomform_template.ui \
         constraintstudentssethomeroomform_template.ui \
         modifyconstraintstudentssethomeroomform_template.ui \
         addconstraintstudentssethomeroomsform_template.ui \
         constraintstudentssethomeroomsform_template.ui \
         modifyconstraintstudentssethomeroomsform_template.ui \
\
           addconstraintstudentssetmaxbuildingchangesperdayform_template.ui \
           constraintstudentssetmaxbuildingchangesperdayform_template.ui \
           modifyconstraintstudentssetmaxbuildingchangesperdayform_template.ui \
           addconstraintstudentsmaxbuildingchangesperdayform_template.ui \
           constraintstudentsmaxbuildingchangesperdayform_template.ui \
           modifyconstraintstudentsmaxbuildingchangesperdayform_template.ui \
           addconstraintstudentssetmaxbuildingchangesperweekform_template.ui \
           constraintstudentssetmaxbuildingchangesperweekform_template.ui \
           modifyconstraintstudentssetmaxbuildingchangesperweekform_template.ui \
           addconstraintstudentsmaxbuildingchangesperweekform_template.ui \
           constraintstudentsmaxbuildingchangesperweekform_template.ui \
           modifyconstraintstudentsmaxbuildingchangesperweekform_template.ui \
           addconstraintstudentssetmingapsbetweenbuildingchangesform_template.ui \
           constraintstudentssetmingapsbetweenbuildingchangesform_template.ui \
           modifyconstraintstudentssetmingapsbetweenbuildingchangesform_template.ui \
           addconstraintstudentsmingapsbetweenbuildingchangesform_template.ui \
           constraintstudentsmingapsbetweenbuildingchangesform_template.ui \
           modifyconstraintstudentsmingapsbetweenbuildingchangesform_template.ui \
\
           addconstraintteachermaxbuildingchangesperdayform_template.ui \
           constraintteachermaxbuildingchangesperdayform_template.ui \
           modifyconstraintteachermaxbuildingchangesperdayform_template.ui \
           addconstraintteachersmaxbuildingchangesperdayform_template.ui \
           constraintteachersmaxbuildingchangesperdayform_template.ui \
           modifyconstraintteachersmaxbuildingchangesperdayform_template.ui \
           addconstraintteachermaxbuildingchangesperweekform_template.ui \
           constraintteachermaxbuildingchangesperweekform_template.ui \
           modifyconstraintteachermaxbuildingchangesperweekform_template.ui \
           addconstraintteachersmaxbuildingchangesperweekform_template.ui \
           constraintteachersmaxbuildingchangesperweekform_template.ui \
           modifyconstraintteachersmaxbuildingchangesperweekform_template.ui \
           addconstraintteachermingapsbetweenbuildingchangesform_template.ui \
           constraintteachermingapsbetweenbuildingchangesform_template.ui \
           modifyconstraintteachermingapsbetweenbuildingchangesform_template.ui \
           addconstraintteachersmingapsbetweenbuildingchangesform_template.ui \
           constraintteachersmingapsbetweenbuildingchangesform_template.ui \
           modifyconstraintteachersmingapsbetweenbuildingchangesform_template.ui \
\
         addconstraintteacherhomeroomform_template.ui \
         constraintteacherhomeroomform_template.ui \
         modifyconstraintteacherhomeroomform_template.ui \
         addconstraintteacherhomeroomsform_template.ui \
         constraintteacherhomeroomsform_template.ui \
         modifyconstraintteacherhomeroomsform_template.ui \
         addconstraintactivitypreferredroomsform_template.ui \
         constraintactivitypreferredroomsform_template.ui \
         modifyconstraintactivitypreferredroomsform_template.ui \
         alltimeconstraintsform_template.ui \
         allspaceconstraintsform_template.ui \
         groupsform_template.ui \
         subgroupsform_template.ui \
         subjectsform_template.ui \
         activitytagsform_template.ui \
         teachersform_template.ui \
         timetablegenerateform_template.ui \
         timetablegeneratemultipleform_template.ui \
         timetableviewstudentsform_template.ui \
         timetableviewroomsform_template.ui \
         yearsform_template.ui \
         timetableshowconflictsform_template.ui \
         timetableviewteachersform_template.ui \
         daysform_template.ui \
         hoursform_template.ui \
         roomsform_template.ui \
         buildingsform_template.ui \
         \
         constraintactivitiespreferredtimeslotsform_template.ui \
         addconstraintactivitiespreferredtimeslotsform_template.ui \
         constraintactivitiespreferredstartingtimesform_template.ui \
         addconstraintactivitiespreferredstartingtimesform_template.ui \
         \
         constraintsubactivitiespreferredtimeslotsform_template.ui \
         addconstraintsubactivitiespreferredtimeslotsform_template.ui \
         constraintsubactivitiespreferredstartingtimesform_template.ui \
         addconstraintsubactivitiespreferredstartingtimesform_template.ui \
         modifyconstraintsubactivitiespreferredtimeslotsform_template.ui \
         modifyconstraintsubactivitiespreferredstartingtimesform_template.ui \
         \
         constraintactivitiessamestartingtimeform_template.ui \
         addconstraintactivitiessamestartingtimeform_template.ui \
\
         constraintactivitiessamestartinghourform_template.ui \
         addconstraintactivitiessamestartinghourform_template.ui \
\
         constraintactivitiessamestartingdayform_template.ui \
         addconstraintactivitiessamestartingdayform_template.ui \
         modifyconstraintactivitiessamestartingdayform_template.ui \
\
		 constraintteachernotavailabletimesform_template.ui \
		 addconstraintteachernotavailabletimesform_template.ui \
		 modifyconstraintteachernotavailabletimesform_template.ui \
		   constraintbasiccompulsorytimeform_template.ui \
		   addconstraintbasiccompulsorytimeform_template.ui \
		   modifyconstraintbasiccompulsorytimeform_template.ui \
		   constraintbasiccompulsoryspaceform_template.ui \
		   addconstraintbasiccompulsoryspaceform_template.ui \
		   modifyconstraintbasiccompulsoryspaceform_template.ui \
		   constraintstudentssetnotavailabletimesform_template.ui \
		   addconstraintstudentssetnotavailabletimesform_template.ui \
		   modifyconstraintstudentssetnotavailabletimesform_template.ui \
		   constraintbreaktimesform_template.ui \
		   addconstraintbreaktimesform_template.ui \
		   modifyconstraintbreaktimesform_template.ui \
		   constraintteachermaxdaysperweekform_template.ui \
		   addconstraintteachermaxdaysperweekform_template.ui \
		   modifyconstraintteachermaxdaysperweekform_template.ui \
\
		   constraintteacherintervalmaxdaysperweekform_template.ui \
		   addconstraintteacherintervalmaxdaysperweekform_template.ui \
		   modifyconstraintteacherintervalmaxdaysperweekform_template.ui \
\
		   constraintstudentssetintervalmaxdaysperweekform_template.ui \
		   addconstraintstudentssetintervalmaxdaysperweekform_template.ui \
		   modifyconstraintstudentssetintervalmaxdaysperweekform_template.ui \
\
		   constraintstudentsintervalmaxdaysperweekform_template.ui \
		   addconstraintstudentsintervalmaxdaysperweekform_template.ui \
		   modifyconstraintstudentsintervalmaxdaysperweekform_template.ui \
\
		   constraintteachersintervalmaxdaysperweekform_template.ui \
		   addconstraintteachersintervalmaxdaysperweekform_template.ui \
		   modifyconstraintteachersintervalmaxdaysperweekform_template.ui \
\
		   constraintteachersmaxhoursdailyform_template.ui \
		   addconstraintteachersmaxhoursdailyform_template.ui \
		   modifyconstraintteachersmaxhoursdailyform_template.ui \
		   constraintteachermaxhoursdailyform_template.ui \
		   addconstraintteachermaxhoursdailyform_template.ui \
		   modifyconstraintteachermaxhoursdailyform_template.ui \
\
		   constraintteachersmaxhourscontinuouslyform_template.ui \
		   addconstraintteachersmaxhourscontinuouslyform_template.ui \
		   modifyconstraintteachersmaxhourscontinuouslyform_template.ui \
		   constraintteachermaxhourscontinuouslyform_template.ui \
		   addconstraintteachermaxhourscontinuouslyform_template.ui \
		   modifyconstraintteachermaxhourscontinuouslyform_template.ui \
\
		   constraintteachersactivitytagmaxhourscontinuouslyform_template.ui \
		   addconstraintteachersactivitytagmaxhourscontinuouslyform_template.ui \
		   modifyconstraintteachersactivitytagmaxhourscontinuouslyform_template.ui \
		   constraintteacheractivitytagmaxhourscontinuouslyform_template.ui \
		   addconstraintteacheractivitytagmaxhourscontinuouslyform_template.ui \
		   modifyconstraintteacheractivitytagmaxhourscontinuouslyform_template.ui \
\
		   constraintteachersminhoursdailyform_template.ui \
		   addconstraintteachersminhoursdailyform_template.ui \
		   modifyconstraintteachersminhoursdailyform_template.ui \
		   constraintteacherminhoursdailyform_template.ui \
		   addconstraintteacherminhoursdailyform_template.ui \
		   modifyconstraintteacherminhoursdailyform_template.ui \
		   constraintactivitypreferredstartingtimeform_template.ui \
		   addconstraintactivitypreferredstartingtimeform_template.ui \
		   modifyconstraintactivitypreferredstartingtimeform_template.ui \
		   constraintactivityendsstudentsdayform_template.ui \
		   addconstraintactivityendsstudentsdayform_template.ui \
		   modifyconstraintactivityendsstudentsdayform_template.ui \
\
		   constraintactivitiesendstudentsdayform_template.ui \
		   addconstraintactivitiesendstudentsdayform_template.ui \
		   modifyconstraintactivitiesendstudentsdayform_template.ui \
\
		   constraintstudentssetmaxgapsperweekform_template.ui \
		   addconstraintstudentssetmaxgapsperweekform_template.ui \
		   modifyconstraintstudentssetmaxgapsperweekform_template.ui \
		   constraintstudentsmaxgapsperweekform_template.ui \
		   addconstraintstudentsmaxgapsperweekform_template.ui \
		   modifyconstraintstudentsmaxgapsperweekform_template.ui \
		   constraintteachersmaxgapsperweekform_template.ui \
		   addconstraintteachersmaxgapsperweekform_template.ui \
		   modifyconstraintteachersmaxgapsperweekform_template.ui \
		   constraintteachermaxgapsperweekform_template.ui \
		   addconstraintteachermaxgapsperweekform_template.ui \
		   modifyconstraintteachermaxgapsperweekform_template.ui \
		   constraintteachersmaxgapsperdayform_template.ui \
		   addconstraintteachersmaxgapsperdayform_template.ui \
		   modifyconstraintteachersmaxgapsperdayform_template.ui \
		   constraintteachermaxgapsperdayform_template.ui \
		   addconstraintteachermaxgapsperdayform_template.ui \
		   modifyconstraintteachermaxgapsperdayform_template.ui \
		   constraintstudentsearlymaxbeginningsatsecondhourform_template.ui \
		   addconstraintstudentsearlymaxbeginningsatsecondhourform_template.ui \
		   modifyconstraintstudentsearlymaxbeginningsatsecondhourform_template.ui \
		   constraintstudentssetearlymaxbeginningsatsecondhourform_template.ui \
		   addconstraintstudentssetearlymaxbeginningsatsecondhourform_template.ui \
		   modifyconstraintstudentssetearlymaxbeginningsatsecondhourform_template.ui \
\
		   constraintstudentssetmaxhoursdailyform_template.ui \
		   addconstraintstudentssetmaxhoursdailyform_template.ui \
		   modifyconstraintstudentssetmaxhoursdailyform_template.ui \
		   constraintstudentsmaxhoursdailyform_template.ui \
		   addconstraintstudentsmaxhoursdailyform_template.ui \
		   modifyconstraintstudentsmaxhoursdailyform_template.ui \
\
		   constraintstudentssetmaxhourscontinuouslyform_template.ui \
		   addconstraintstudentssetmaxhourscontinuouslyform_template.ui \
		   modifyconstraintstudentssetmaxhourscontinuouslyform_template.ui \
		   constraintstudentsmaxhourscontinuouslyform_template.ui \
		   addconstraintstudentsmaxhourscontinuouslyform_template.ui \
		   modifyconstraintstudentsmaxhourscontinuouslyform_template.ui \
\
		   constraintstudentssetactivitytagmaxhourscontinuouslyform_template.ui \
		   addconstraintstudentssetactivitytagmaxhourscontinuouslyform_template.ui \
		   modifyconstraintstudentssetactivitytagmaxhourscontinuouslyform_template.ui \
		   constraintstudentsactivitytagmaxhourscontinuouslyform_template.ui \
		   addconstraintstudentsactivitytagmaxhourscontinuouslyform_template.ui \
		   modifyconstraintstudentsactivitytagmaxhourscontinuouslyform_template.ui \
\
		   constraintstudentssetminhoursdailyform_template.ui \
		   addconstraintstudentssetminhoursdailyform_template.ui \
		   modifyconstraintstudentssetminhoursdailyform_template.ui \
		   constraintstudentsminhoursdailyform_template.ui \
		   addconstraintstudentsminhoursdailyform_template.ui \
		   modifyconstraintstudentsminhoursdailyform_template.ui \
		   constraintactivitiesnotoverlappingform_template.ui \
		   addconstraintactivitiesnotoverlappingform_template.ui \
		   modifyconstraintactivitiesnotoverlappingform_template.ui \
\
		   constraint2activitiesconsecutiveform_template.ui \
		   addconstraint2activitiesconsecutiveform_template.ui \
		   modifyconstraint2activitiesconsecutiveform_template.ui \
\
		   constraint2activitiesgroupedform_template.ui \
		   addconstraint2activitiesgroupedform_template.ui \
		   modifyconstraint2activitiesgroupedform_template.ui \
\
		   constraint2activitiesorderedform_template.ui \
		   addconstraint2activitiesorderedform_template.ui \
		   modifyconstraint2activitiesorderedform_template.ui \
\
		   constraintminndaysbetweenactivitiesform_template.ui \
		   addconstraintminndaysbetweenactivitiesform_template.ui \
		   modifyconstraintminndaysbetweenactivitiesform_template.ui \
\
		   constraintmingapsbetweenactivitiesform_template.ui \
		   addconstraintmingapsbetweenactivitiesform_template.ui \
		   modifyconstraintmingapsbetweenactivitiesform_template.ui \
\
		   constraintactivitypreferredtimeslotsform_template.ui \
           modifyconstraintactivitiespreferredtimeslotsform_template.ui \
		   constraintactivitypreferredstartingtimesform_template.ui \
           modifyconstraintactivitiespreferredstartingtimesform_template.ui \
		   modifyconstraintactivitiessamestartingtimeform_template.ui \
		   modifyconstraintactivitiessamestartinghourform_template.ui \
		   institutionnameform_template.ui \
		   commentsform_template.ui \
		   splityearform_template.ui

TEMPLATE = app 
CONFIG += release \
          warn_on \
          qt \
          thread 
DESTDIR = ../../
TARGET = fet 
OBJECTS_DIR = ../../tmp 
UI_DIR = ../../tmp 
MOC_DIR = ../../tmp 
INCLUDEPATH = ../engine 
#The following line was inserted by qt3to4
QT += xml qt3support network
#The following line was inserted by qt3to4
CONFIG += uic3

