# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

TEMPLATE = subdirs
CONFIG += release \
warn_on \
qt \
thread
MOC_DIR = tmp
OBJECTS_DIR = tmp
UI_DIR = tmp
SUBDIRS += src 
